internal.key.converter.schemas.enable=false
group.id=streaming-pipeline-connect-cluster
value.converter.schemas.enable=false
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.json.JsonConverter
config.storage.topic=connect-configs
log4j.loggers=org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR
offset.storage.replication.factor=1
plugin.path=/usr/share/java,/usr/share/confluent-hub-components
log4j.root.loglevel=INFO
offset.storage.topic=connect-offsets
key.converter.schemas.enable=false
bootstrap.servers=kafka:9092
value.converter=org.apache.kafka.connect.json.JsonConverter
rest.advertised.host.name=kafka-connect
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
rest.port=8083
status.storage.topic=connect-status
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter.schemas.enable=false
config.storage.replication.factor=1
