-- Create database and schemas
CREATE DATABASE IF NOT EXISTS STOCK_MARKET;
USE DATABASE STOCK_MARKET;

CREATE SCHEMA IF NOT EXISTS BATCH;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS UTILS;

-- Create file format for loading data
CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT
    TYPE = 'PARQUET'
    COMPRESSION = 'AUTO';

-- Create stage for loading data from S3
CREATE OR REPLACE STAGE STOCK_MARKET_STAGE
    URL = 's3://your-s3-bucket/'
    STORAGE_INTEGRATION = YOUR_S3_INTEGRATION
    FILE_FORMAT = PARQUET_FORMAT;

-- Create logging table
CREATE OR REPLACE TABLE DWH_LOAD_LOGS (
    log_id INTEGER AUTOINCREMENT START 1 INCREMENT 1,
    batch_id STRING NOT NULL,
    process_name STRING NOT NULL,
    status STRING NOT NULL,
    records_processed INTEGER,
    error_message STRING,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT pk_dwh_load_logs PRIMARY KEY (log_id)
);

-- Create utility functions
CREATE OR REPLACE FUNCTION GET_BUSINESS_DAYS(
    start_date DATE, 
    end_date DATE
) 
RETURNS INTEGER
AS $$
    SELECT COUNT(*) 
    FROM DIM_DATE 
    WHERE date_id BETWEEN start_date AND end_date 
    AND is_trading_day = TRUE
$$;

-- Grant permissions
GRANT USAGE ON DATABASE STOCK_MARKET TO ROLE YOUR_ROLE;
GRANT USAGE ON SCHEMA BATCH TO ROLE YOUR_ROLE;
GRANT USAGE ON SCHEMA STAGING TO ROLE YOUR_ROLE;
GRANT USAGE ON SCHEMA UTILS TO ROLE YOUR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA BATCH TO ROLE YOUR_ROLE;
GRANT SELECT, INSERT, TRUNCATE ON ALL TABLES IN SCHEMA STAGING TO ROLE YOUR_ROLE;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA UTILS TO ROLE YOUR_ROLE;
