-- Snowflake Setup for Streaming Pipeline
-- This script sets up the complete Snowflake environment for the streaming data pipeline

-- =====================================================
-- 1. DATABASE AND SCHEMA SETUP
-- =====================================================

-- Create database and schemas
CREATE DATABASE IF NOT EXISTS STOCK_MARKET;
USE DATABASE STOCK_MARKET;

CREATE SCHEMA IF NOT EXISTS STREAMING;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS UTILS;

-- Set default schema
USE SCHEMA STREAMING;

-- =====================================================
-- 2. FILE FORMATS
-- =====================================================

-- Parquet file format for streaming data
CREATE OR REPLACE FILE FORMAT STREAMING.PARQUET_FORMAT
    TYPE = 'PARQUET'
    COMPRESSION = 'AUTO'
    BINARY_AS_TEXT = FALSE;

-- JSON file format for metadata
CREATE OR REPLACE FILE FORMAT STREAMING.JSON_FORMAT
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    IGNORE_UTF8_ERRORS = FALSE;

-- =====================================================
-- 3. STORAGE INTEGRATION AND STAGES
-- =====================================================

-- Create storage integration (replace with your actual values)
CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::123456789012:role/snowflake-s3-role'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://your-bucket-name/staging/',
        's3://your-bucket-name/processed/'
    );

-- Show integration details (run this to get the external ID and user ARN)
-- DESC STORAGE INTEGRATION S3_INTEGRATION;

-- Create external stages
CREATE OR REPLACE STAGE STREAMING.STREAMING_STAGE
    URL = 's3://your-bucket-name/staging/streaming/'
    STORAGE_INTEGRATION = S3_INTEGRATION
    FILE_FORMAT = STREAMING.PARQUET_FORMAT;

CREATE OR REPLACE STAGE STREAMING.PROCESSED_STAGE
    URL = 's3://your-bucket-name/processed/streaming/'
    STORAGE_INTEGRATION = S3_INTEGRATION
    FILE_FORMAT = STREAMING.PARQUET_FORMAT;

-- =====================================================
-- 4. DIMENSION TABLES
-- =====================================================

-- DIM_COMPANY: Company information with SCD Type 2
CREATE OR REPLACE TABLE STREAMING.DIM_COMPANY (
    COMPANY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SYMBOL VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(255),
    SECTOR VARCHAR(100),
    INDUSTRY VARCHAR(100),
    MARKET_CAP_CATEGORY VARCHAR(20),
    EXCHANGE VARCHAR(10),
    CURRENCY VARCHAR(3),
    COUNTRY VARCHAR(50),
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- DIM_DATE: Date dimension
CREATE OR REPLACE TABLE STREAMING.DIM_DATE (
    DATE_KEY NUMBER PRIMARY KEY,
    DATE_VALUE DATE NOT NULL,
    YEAR NUMBER,
    QUARTER NUMBER,
    MONTH NUMBER,
    MONTH_NAME VARCHAR(20),
    DAY_OF_MONTH NUMBER,
    DAY_OF_WEEK NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_OF_YEAR NUMBER,
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN,
    IS_TRADING_DAY BOOLEAN,
    FISCAL_YEAR NUMBER,
    FISCAL_QUARTER NUMBER
);

-- DIM_TIME: Time dimension with market sessions
CREATE OR REPLACE TABLE STREAMING.DIM_TIME (
    TIME_KEY NUMBER PRIMARY KEY,
    TIME_VALUE TIME NOT NULL,
    HOUR NUMBER,
    MINUTE NUMBER,
    SECOND NUMBER,
    HOUR_MINUTE VARCHAR(5),
    AM_PM VARCHAR(2),
    MARKET_SESSION VARCHAR(20), -- 'PRE_MARKET', 'REGULAR', 'AFTER_HOURS', 'CLOSED'
    TRADING_DAY_MINUTE NUMBER -- Minutes since market open
);

-- =====================================================
-- 5. FACT TABLES
-- =====================================================

-- FACT_STOCK_PRICES: Main fact table for stock prices
CREATE OR REPLACE TABLE STREAMING.FACT_STOCK_PRICES (
    PRICE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_KEY NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,
    TIME_KEY NUMBER NOT NULL,
    OPEN_PRICE DECIMAL(18,4),
    HIGH_PRICE DECIMAL(18,4),
    LOW_PRICE DECIMAL(18,4),
    CLOSE_PRICE DECIMAL(18,4),
    VOLUME NUMBER,
    ADJUSTED_CLOSE DECIMAL(18,4),
    DIVIDEND_AMOUNT DECIMAL(18,4),
    SPLIT_COEFFICIENT DECIMAL(10,6),
    
    -- Technical Indicators
    SMA_20 DECIMAL(18,4),
    SMA_50 DECIMAL(18,4),
    EMA_12 DECIMAL(18,4),
    EMA_26 DECIMAL(18,4),
    RSI_14 DECIMAL(8,4),
    MACD DECIMAL(18,4),
    MACD_SIGNAL DECIMAL(18,4),
    
    -- Metadata
    DATA_SOURCE VARCHAR(50),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    PROCESSING_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    FOREIGN KEY (COMPANY_KEY) REFERENCES STREAMING.DIM_COMPANY(COMPANY_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES STREAMING.DIM_DATE(DATE_KEY),
    FOREIGN KEY (TIME_KEY) REFERENCES STREAMING.DIM_TIME(TIME_KEY)
)
CLUSTER BY (COMPANY_KEY, DATE_KEY, TIME_KEY);

-- FACT_TRADING_VOLUME: Trading volume metrics
CREATE OR REPLACE TABLE STREAMING.FACT_TRADING_VOLUME (
    VOLUME_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY_KEY NUMBER NOT NULL,
    DATE_KEY NUMBER NOT NULL,
    TIME_KEY NUMBER NOT NULL,
    VOLUME NUMBER NOT NULL,
    VOLUME_WEIGHTED_PRICE DECIMAL(18,4),
    TRADE_COUNT NUMBER,
    BUY_VOLUME NUMBER,
    SELL_VOLUME NUMBER,
    
    -- Volume Indicators
    VOLUME_SMA_20 NUMBER,
    VOLUME_RATIO DECIMAL(8,4), -- Current volume / Average volume
    
    -- Metadata
    DATA_SOURCE VARCHAR(50),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    PROCESSING_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    FOREIGN KEY (COMPANY_KEY) REFERENCES STREAMING.DIM_COMPANY(COMPANY_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES STREAMING.DIM_DATE(DATE_KEY),
    FOREIGN KEY (TIME_KEY) REFERENCES STREAMING.DIM_TIME(TIME_KEY)
)
CLUSTER BY (COMPANY_KEY, DATE_KEY, TIME_KEY);

-- =====================================================
-- 6. UTILITY AND MONITORING TABLES
-- =====================================================

-- Data quality monitoring
CREATE OR REPLACE TABLE STREAMING.DATA_QUALITY_RESULTS (
    QUALITY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TABLE_NAME VARCHAR(100) NOT NULL,
    CHECK_NAME VARCHAR(100) NOT NULL,
    CHECK_TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    RECORD_COUNT NUMBER,
    ERROR_COUNT NUMBER,
    ERROR_PERCENTAGE DECIMAL(5,2),
    CHECK_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ERROR_DETAILS VARIANT
);

-- Pipeline monitoring
CREATE OR REPLACE TABLE STREAMING.PIPELINE_MONITORING (
    MONITOR_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PIPELINE_NAME VARCHAR(100) NOT NULL,
    BATCH_ID VARCHAR(100),
    STATUS VARCHAR(20) NOT NULL,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    RECORDS_PROCESSED NUMBER,
    RECORDS_FAILED NUMBER,
    ERROR_MESSAGE VARCHAR(1000),
    PROCESSING_DURATION_SECONDS NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Load history tracking
CREATE OR REPLACE TABLE STREAMING.LOAD_HISTORY (
    LOAD_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TABLE_NAME VARCHAR(100) NOT NULL,
    FILE_NAME VARCHAR(500),
    S3_KEY VARCHAR(1000),
    LOAD_STATUS VARCHAR(20) NOT NULL,
    RECORDS_LOADED NUMBER,
    LOAD_START_TIME TIMESTAMP_NTZ,
    LOAD_END_TIME TIMESTAMP_NTZ,
    ERROR_MESSAGE VARCHAR(1000),
    SNOWPIPE_NAME VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =====================================================
-- 7. SNOWPIPES FOR AUTOMATIC LOADING
-- =====================================================

-- Snowpipe for stock prices
CREATE OR REPLACE PIPE STREAMING.STOCK_PRICES_PIPE
    AUTO_INGEST = TRUE
    AS
    COPY INTO STREAMING.FACT_STOCK_PRICES
    FROM @STREAMING.STREAMING_STAGE/fact_stock_prices/
    FILE_FORMAT = STREAMING.PARQUET_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE'
    PURGE = TRUE;

-- Snowpipe for trading volume
CREATE OR REPLACE PIPE STREAMING.TRADING_VOLUME_PIPE
    AUTO_INGEST = TRUE
    AS
    COPY INTO STREAMING.FACT_TRADING_VOLUME
    FROM @STREAMING.STREAMING_STAGE/fact_trading_volume/
    FILE_FORMAT = STREAMING.PARQUET_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE'
    PURGE = TRUE;

-- Snowpipe for data quality results
CREATE OR REPLACE PIPE STREAMING.DATA_QUALITY_PIPE
    AUTO_INGEST = TRUE
    AS
    COPY INTO STREAMING.DATA_QUALITY_RESULTS
    FROM @STREAMING.STREAMING_STAGE/data_quality_results/
    FILE_FORMAT = STREAMING.PARQUET_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE'
    PURGE = TRUE;

-- =====================================================
-- 8. POPULATE DIMENSION TABLES
-- =====================================================

-- Populate date dimension (2020-2030)
INSERT INTO STREAMING.DIM_DATE
WITH date_range AS (
    SELECT 
        DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY NULL) - 1, '2020-01-01'::DATE) AS date_value
    FROM TABLE(GENERATOR(ROWCOUNT => DATEDIFF(DAY, '2020-01-01'::DATE, '2030-12-31'::DATE) + 1))
)
SELECT 
    TO_NUMBER(TO_CHAR(date_value, 'YYYYMMDD')) AS DATE_KEY,
    date_value AS DATE_VALUE,
    YEAR(date_value) AS YEAR,
    QUARTER(date_value) AS QUARTER,
    MONTH(date_value) AS MONTH,
    MONTHNAME(date_value) AS MONTH_NAME,
    DAY(date_value) AS DAY_OF_MONTH,
    DAYOFWEEK(date_value) AS DAY_OF_WEEK,
    DAYNAME(date_value) AS DAY_NAME,
    WEEKOFYEAR(date_value) AS WEEK_OF_YEAR,
    CASE WHEN DAYOFWEEK(date_value) IN (1, 7) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
    FALSE AS IS_HOLIDAY,  -- Can be updated with holiday logic
    CASE WHEN DAYOFWEEK(date_value) BETWEEN 2 AND 6 THEN TRUE ELSE FALSE END AS IS_TRADING_DAY,
    YEAR(date_value) AS FISCAL_YEAR,  -- Assuming calendar year = fiscal year
    QUARTER(date_value) AS FISCAL_QUARTER
FROM date_range;

-- Populate time dimension (minute-level granularity)
INSERT INTO STREAMING.DIM_TIME
WITH time_range AS (
    SELECT 
        TIME_FROM_PARTS(
            FLOOR((ROW_NUMBER() OVER (ORDER BY NULL) - 1) / 60),
            MOD(ROW_NUMBER() OVER (ORDER BY NULL) - 1, 60),
            0
        ) AS time_value
    FROM TABLE(GENERATOR(ROWCOUNT => 1440))  -- 24 hours * 60 minutes
)
SELECT 
    HOUR(time_value) * 100 + MINUTE(time_value) AS TIME_KEY,
    time_value AS TIME_VALUE,
    HOUR(time_value) AS HOUR,
    MINUTE(time_value) AS MINUTE,
    0 AS SECOND,
    TO_CHAR(time_value, 'HH24:MI') AS HOUR_MINUTE,
    CASE WHEN HOUR(time_value) < 12 THEN 'AM' ELSE 'PM' END AS AM_PM,
    CASE 
        WHEN HOUR(time_value) BETWEEN 4 AND 9 AND MINUTE(time_value) <= 30 THEN 'PRE_MARKET'
        WHEN HOUR(time_value) BETWEEN 9 AND 16 THEN 'REGULAR'
        WHEN HOUR(time_value) BETWEEN 16 AND 20 THEN 'AFTER_HOURS'
        ELSE 'CLOSED'
    END AS MARKET_SESSION,
    CASE 
        WHEN HOUR(time_value) >= 9 AND HOUR(time_value) < 16 THEN
            (HOUR(time_value) - 9) * 60 + MINUTE(time_value)
        ELSE NULL
    END AS TRADING_DAY_MINUTE
FROM time_range;

-- Insert sample companies (you can expand this list)
INSERT INTO STREAMING.DIM_COMPANY 
(SYMBOL, COMPANY_NAME, SECTOR, INDUSTRY, MARKET_CAP_CATEGORY, EXCHANGE, CURRENCY, COUNTRY, EFFECTIVE_DATE, IS_CURRENT)
VALUES
('AAPL', 'Apple Inc.', 'Technology', 'Consumer Electronics', 'Large Cap', 'NASDAQ', 'USD', 'USA', '2020-01-01', TRUE),
('GOOGL', 'Alphabet Inc.', 'Technology', 'Internet Services', 'Large Cap', 'NASDAQ', 'USD', 'USA', '2020-01-01', TRUE),
('MSFT', 'Microsoft Corporation', 'Technology', 'Software', 'Large Cap', 'NASDAQ', 'USD', 'USA', '2020-01-01', TRUE),
('AMZN', 'Amazon.com Inc.', 'Consumer Discretionary', 'E-commerce', 'Large Cap', 'NASDAQ', 'USD', 'USA', '2020-01-01', TRUE),
('TSLA', 'Tesla Inc.', 'Consumer Discretionary', 'Electric Vehicles', 'Large Cap', 'NASDAQ', 'USD', 'USA', '2020-01-01', TRUE),
('NVDA', 'NVIDIA Corporation', 'Technology', 'Semiconductors', 'Large Cap', 'NASDAQ', 'USD', 'USA', '2020-01-01', TRUE),
('META', 'Meta Platforms Inc.', 'Technology', 'Social Media', 'Large Cap', 'NASDAQ', 'USD', 'USA', '2020-01-01', TRUE),
('NFLX', 'Netflix Inc.', 'Communication Services', 'Streaming', 'Large Cap', 'NASDAQ', 'USD', 'USA', '2020-01-01', TRUE);

-- =====================================================
-- 9. SEARCH OPTIMIZATION (Optional - requires Enterprise edition)
-- =====================================================

-- Add search optimization for frequently queried columns
-- ALTER TABLE STREAMING.DIM_COMPANY ADD SEARCH OPTIMIZATION ON EQUALITY(SYMBOL);
-- ALTER TABLE STREAMING.FACT_STOCK_PRICES ADD SEARCH OPTIMIZATION ON EQUALITY(COMPANY_KEY, DATE_KEY);
-- ALTER TABLE STREAMING.FACT_TRADING_VOLUME ADD SEARCH OPTIMIZATION ON EQUALITY(COMPANY_KEY, DATE_KEY);

-- =====================================================
-- 10. VIEWS FOR ANALYTICS
-- =====================================================

-- Create a view for current stock prices with company information
CREATE OR REPLACE VIEW STREAMING.V_CURRENT_STOCK_PRICES AS
SELECT 
    c.SYMBOL,
    c.COMPANY_NAME,
    c.SECTOR,
    c.INDUSTRY,
    p.CLOSE_PRICE,
    p.VOLUME,
    p.SMA_20,
    p.SMA_50,
    p.RSI_14,
    d.DATE_VALUE,
    t.TIME_VALUE,
    t.MARKET_SESSION,
    p.PROCESSING_TIMESTAMP
FROM STREAMING.FACT_STOCK_PRICES p
JOIN STREAMING.DIM_COMPANY c ON p.COMPANY_KEY = c.COMPANY_KEY
JOIN STREAMING.DIM_DATE d ON p.DATE_KEY = d.DATE_KEY
JOIN STREAMING.DIM_TIME t ON p.TIME_KEY = t.TIME_KEY
WHERE c.IS_CURRENT = TRUE
  AND p.PROCESSING_TIMESTAMP >= DATEADD(DAY, -1, CURRENT_TIMESTAMP());

-- Create a view for daily trading summary
CREATE OR REPLACE VIEW STREAMING.V_DAILY_TRADING_SUMMARY AS
SELECT 
    c.SYMBOL,
    c.COMPANY_NAME,
    d.DATE_VALUE,
    MIN(p.LOW_PRICE) as DAY_LOW,
    MAX(p.HIGH_PRICE) as DAY_HIGH,
    FIRST_VALUE(p.OPEN_PRICE) OVER (PARTITION BY c.SYMBOL, d.DATE_VALUE ORDER BY t.TIME_VALUE) as DAY_OPEN,
    LAST_VALUE(p.CLOSE_PRICE) OVER (PARTITION BY c.SYMBOL, d.DATE_VALUE ORDER BY t.TIME_VALUE) as DAY_CLOSE,
    SUM(p.VOLUME) as TOTAL_VOLUME,
    COUNT(*) as PRICE_UPDATES
FROM STREAMING.FACT_STOCK_PRICES p
JOIN STREAMING.DIM_COMPANY c ON p.COMPANY_KEY = c.COMPANY_KEY
JOIN STREAMING.DIM_DATE d ON p.DATE_KEY = d.DATE_KEY
JOIN STREAMING.DIM_TIME t ON p.TIME_KEY = t.TIME_KEY
WHERE c.IS_CURRENT = TRUE
  AND d.IS_TRADING_DAY = TRUE
GROUP BY c.SYMBOL, c.COMPANY_NAME, d.DATE_VALUE;

-- =====================================================
-- 11. GRANTS AND PERMISSIONS
-- =====================================================

-- Grant permissions to roles (adjust role names as needed)
GRANT USAGE ON DATABASE STOCK_MARKET TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA STREAMING TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA STAGING TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA UTILS TO ROLE SYSADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STREAMING TO ROLE SYSADMIN;
GRANT SELECT, INSERT, TRUNCATE ON ALL TABLES IN SCHEMA STAGING TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA STREAMING TO ROLE SYSADMIN;

-- Grant permissions for Snowpipes
GRANT OPERATE ON ALL PIPES IN SCHEMA STREAMING TO ROLE SYSADMIN;

-- =====================================================
-- 12. MONITORING QUERIES
-- =====================================================

-- Query to check Snowpipe status
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
--     DATE_RANGE_START=>DATEADD('DAY',-1,CURRENT_DATE()),
--     DATE_RANGE_END=>CURRENT_DATE(),
--     PIPE_NAME=>'STREAMING.STOCK_PRICES_PIPE'
-- ));

-- Query to check recent loads
-- SELECT * FROM STREAMING.LOAD_HISTORY 
-- WHERE CREATED_AT >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
-- ORDER BY CREATED_AT DESC;

-- Query to check data quality results
-- SELECT * FROM STREAMING.DATA_QUALITY_RESULTS 
-- WHERE CHECK_TIMESTAMP >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
-- ORDER BY CHECK_TIMESTAMP DESC;

-- =====================================================
-- SETUP COMPLETE
-- =====================================================

-- Show pipe notification channels (run this to get SNS topic ARNs for AWS setup)
SHOW PIPES IN SCHEMA STREAMING;